export const SET_LIKES = 'SET_LIKES';
export const DELETE_LIKES = 'SET_LIKES';
export const RESET_LIKES = 'SET_LIKES';
export const  CHARACTERS_REQUEST = 'CHARACTERS_REQUEST';
export const  CHARACTERS_SUCCES = 'CHARACTERS_SUCCES';
export const CHARACTERS_ERROR = 'CHARACTERS_ERROR';